striker1826/DMMHN_Next.js

src/api/question/questionApi.ts
src/api/user/userApi.ts
src/app/(home)/page.module.scss
src/app/interview/layout.tsx
src/app/interview/page.module.scss
src/components/interview/End/index.tsx
src/components/interview/Ready/index.tsx
src/components/interview/Start/Start.module.scss
src/components/interview/Start/index.tsx
src/components/user/UserProfile/index.tsx
src/middleware.ts
src/models/simulation/video.ts
src/shared/types/question.ts
src/shared/utils/axios.ts
src/shared/utils/cookies.ts
src/widgets/Header/Header.module.scss
src/widgets/Header/Header.tsx
src/widgets/interview/Simulation/index.module.scss
src/widgets/interview/Simulation/index.tsx

feat: interview simulation 기능 구현

---

src/app/(auth)/kakao/redirect/page.tsx
src/app/(auth)/signin/page.tsx

fix: vercel 환경에서 login 안되는 문제 fix 중

---

src/app/(auth)/signin/page.tsx

fix: vercel 환경에서 login 안되는 문제 해결 중

---

.env
next.config.mjs
src/api/auth/kakaoLogin.ts
src/app/(auth)/kakao/redirect/page.tsx
src/app/(auth)/signin/page.tsx
src/components/interview/Start/index.tsx
src/shared/utils/axios.ts

feat: .env들 추가

---

src/components/interview/Start/index.tsx
src/models/simulation/useHandleInterview.ts
src/widgets/interview/Simulation/index.tsx

refactor: simulation 페이지 로직 분리

---

src/widgets/interview/Simulation/index.tsx

fix: 로그인이 되어있는 상태에서도 /signin 페이지로 리다이렉트 되는 문제 fixed

---

src/components/interview/End/End.module.scss
src/components/interview/Start/index.tsx
src/shared/components/Button/SimulationBtn/SimulationBtn.module.scss
src/shared/components/Button/SimulationBtn/SimulationBtn.tsx

refactor: Simulation Button들 컴포넌트로 분리하기

---

src/components/interview/Start/index.tsx
src/models/simulation/getSpeech.ts
src/models/simulation/useHandleInterview.ts

feat: TTS 기능 추가

---

src/app/interview/Simulation.tsx
src/app/interview/layout.tsx
src/app/interview/page.module.scss
src/app/interview/page.tsx
src/middleware.ts
src/shared/utils/protectRoute.ts
src/widgets/interview/Stacks/index.module.scss

- 미들웨어에 인터뷰 라우트로 토큰 없이 접근하면 로그인 페이지로 리다이렉트 하도록 작업해두었습니다.
- 위젯은 세부적으로 건드릴것이 많아 일부 적용 후 얘기해보구 전체 적용하면 될 것 같습니다. (아까 말한 색상 어떤가요..??)

라우트 보안 작업 및 인터뷰 페이지 스타일 일부 변경 후 적용

---

src/app/interview/InterviewContainer.module.scss
src/app/interview/InterviewContainer.tsx
src/app/interview/page.module.scss
src/app/interview/page.tsx
src/component_list/chattingList/ChattingList.module.scss
src/component_list/chattingList/ChattingList.tsx
src/components/chat/chatting/Chatting.module.scss
src/components/chat/chatting/Chatting.tsx
src/models/audio/useSTT.ts
src/models/chat/useHandleChat.ts
src/models/question/useHandleQuestion.ts
src/models/simulation/useHandleInterview.ts
src/queries/question/getQuestionListApi.ts
src/shared/types/question.ts
src/widgets/chat/Chat.module.scss
src/widgets/chat/Chat.tsx
src/widgets/interview/Stacks/Stacks.module.scss
src/widgets/interview/Stacks/index.module.scss
src/widgets/interview/Stacks/index.tsx
src/widgets/interview/Start/Start.module.scss
src/widgets/interview/Start/index.tsx

- 면접 시작 시 안내문구가 나오고 5초 뒤부터 문답이 시작됩니다.
- 문답이 완료되면 문답에 대한 평가를 볼 수 있는 다음 step으로 넘어갈 수 있습니다.

interview 시 문답을 주고받는 채팅 기능 구현

---

src/app/(home)/page.module.scss
src/app/(home)/page.tsx
src/shared/components/Button/Button.module.scss
src/widgets/interview/Ready/Ready.module.scss
src/widgets/interview/Ready/index.tsx

interview 페이지의 ready step UI 변경

refactor: interview 페이지의 ready step UI 변경

---

src/app/(home)/page.tsx

home page에서 interview page로 이동하는 버튼 문구 변경

style: home page에서 interview page로 이동하는 버튼 문구 변경

---

src/app/(home)/page.module.scss
src/app/(home)/page.tsx
src/shared/components/Button/MovePageBtn/MovePageBtn.module.scss

style: home 페이지의 UI 수정

---

src/app/interview/InterviewContainer.tsx
src/models/audio/useSTT.ts
src/models/chat/useHandleChat.ts
src/queries/question/getQuestionListApi.ts
src/queries/stacks/stacksApi.ts
src/shared/utils/sleep.ts
src/widgets/chat/Chat.tsx
src/widgets/interview/Interviewing/index.tsx
src/widgets/interview/Ready/index.tsx
src/widgets/interview/Stacks/index.tsx

질문 List GET 요청 API에 exception 추가
fix: Ready Step에서 녹음된 내용이 Interviewing Step까지 넘어오는 문제 해결
feat: interview page에서 stack 미선택 시 alert 창 띄우는 기능 추가

feat: 질문 List GET 요청 API에 exception 추가 및 transcript 에러 해결

---

src/app/interview/InterviewContainer.module.scss
src/shared/components/Button/PrimaryBtn/PrimaryBtn.module.scss
src/widgets/interview/Stacks/Stacks.module.scss
src/widgets/interview/Stacks/index.tsx

interview 페이지의 Stacks Step tablet 반응형 UI 구현

style: interview 페이지의 Stacks Step tablet 반응형 UI 구현

---

src/widgets/interview/Interviewing/Interviewing.module.scss

interview 페이지의 Interviewing Step 반응형 UI 구현

style: interview 페이지의 Interviewing Step 반응형 UI 구현

---

src/app/(home)/page.module.scss

style: home 페이지 반응형 UI 구현

---

src/app/browser-not-supported/page.tsx
src/app/mobile-page/page.tsx
src/middleware.ts

- macher의 경로를 미들웨어가 체크하지 않을 예외경로만 두어 로그인이 안되는 문제를 해결했습니다.
- 리다이렉트 페이지 ui를 구현했습니다.

feat: 로그인 오류 해결과 리다이렉트 페이지 ui구현

---

src/middleware.ts

vercel 환경에서 middleware가 동작을 안하는 문제 해결 중

fix: vercel 환경에서 middleware가 동작을 안하는 문제 해결 중

---

src/middleware.ts

hotfix: 카카오 로그인 문제 해결중

---

src/component_list/chattingList/ChattingList.tsx
src/components/chat/chatting/Chatting.tsx
src/models/chat/useHandleChat.ts
src/widgets/chat/Chat.tsx

Chat에서 interviewer의 image가 깨지는 문제 수정

hotfix: Chat에서 interviewer의 image가 깨지는 문제 수정

---

src/components/auth/LoginModal/LoginModal.tsx
src/models/chat/useHandleChat.ts
src/widgets/chat/Chat.tsx

질문이 길어졌을 때 이전의 답변이 현재의 답변에 포함되는 문제

hotfix: 질문이 길어졌을 때 이전의 답변이 현재의 답변에 포함되는 문제

---

src/middleware.ts
src/models/chat/useHandleChat.ts
src/widgets/chat/Chat.module.scss
src/widgets/chat/Chat.tsx
src/widgets/interview/Ready/index.tsx

interview chat delay 기능 & interview chat submit button disabled 처리, ready 단계에서 녹음했던 내용이 interviewing으로 전파되는 현상 수정

---

src/app/interview/InterviewContainer.tsx
src/middleware.ts
src/widgets/interview/Feedback/index.tsx

fix: 인증 쿠키 maxAge 초단위로 24시간으로 변경하여 자동 로그아웃 개선

---

src/widgets/interview/Ready/index.tsx

hotfix: interview-ready 녹음 중지 안되는 현상 수정

hotfix: interview-ready 녹음 중지 안되는 현상 수정

---

src/app/interview/InterviewContainer.tsx
src/widgets/interview/Ready/index.tsx

hotfix: ready 단계에서 녹음된 음성이 모의면접의 첫번째 질문에 연결되는 현상 수정

hotfix: ready 단계에서 녹음된 음성이 모의면접의 첫번째 질문에 연결되는 현상 수정

---

src/app/interview/InterviewContainer.tsx
src/models/chat/formatChatData.ts
src/models/chat/useHandleChat.ts
src/shared/types/chat.ts
src/widgets/chat/Chat.module.scss
src/widgets/chat/Chat.tsx
src/widgets/interview/Interviewing/Interviewing.module.scss
src/widgets/interview/Interviewing/index.tsx

feat: interview 도중에 exit 후 피드백을 받는 기능 추가

feat: interview 도중에 exit 후 피드백을 받는 기능 추가

---

src/components/feedback/FeedbackCard.tsx

style: FeedbackCard ellipsis 처리

style: FeedbackCard ellipsis 처리

---

src/components/interview/ReadyInfoCard.tsx
src/components/video/Video.tsx
src/widgets/chat/Chat.tsx
src/widgets/interview/Interviewing/Interviewing.module.scss
src/widgets/interview/Interviewing/index.tsx
src/widgets/interview/Ready/index.tsx

Video 컴포넌트와 interview-Ready-Card 컴포넌트의 borderRadius 통일

style: Video 컴포넌트와 interview-Ready-Card 컴포넌트의 borderRadius 통일

---

src/app/interview/InterviewContainer.tsx
src/components/interview/ReadyInfoCard.tsx
src/components/video/Video.tsx
src/widgets/chat/Chat.tsx
src/widgets/interview/Interviewing/Interviewing.module.scss
src/widgets/interview/Interviewing/index.tsx
src/widgets/interview/Ready/index.tsx

fix: 답변 내용 없이 interview 도중 exit 하는 상황 해결

fix: 답변 내용 없이 interview 도중 exit 하는 상황 해결 
