striker1826/DMMHN_Next.js

- src/models/simulation/video.ts
영상 촬영이 시작되지 않았을 경우에 면접 시작 버튼을 누르면 alert(“화면에 카메라 영상이 나타나면 시작이 가능합니다.) 띄우기
> 영상 촬영이 시작되지 않았을 경우에 면접 시작 버튼을 누르면 alert(“화면에 카메라 영상이 나타나면 시작이 가능합니다.) 띄우기

- src/app/(home)/page.module.scss
- src/app/(home)/page.tsx
- src/app/globals.css
- src/app/interview/page.module.scss
- src/components/user/LogOutBtn/LogOutBtn.module.scss
- src/components/user/LogOutBtn/index.tsx
- src/components/user/UserProfile/UserProfile.module.scss
- src/components/user/UserProfile/index.tsx
- src/shared/utils/protectRoute.ts
- src/widgets/Header/Header.module.scss
- 헤더의 포지션을 absolute로 변경하고 투명색상을 주어 화면 상단에 고정하게끔 하였습니다.
- 배경색으로 인해 로고 텍스트 색상과 로그아웃 버튼의 색상을 #ffffff로 변경했습니다.
- 기존에 background로 들어갔던 이미지를 next/Image로 변경하고 크기를 조정해주었습니다.
- 소개 문구의 정렬을 왼쪽으로 두었고 모의면접 버튼의 크기를 더 크게 해주었습니다.
- 결과물 스크린샷입니다.
> style: 홈(/)페이지의 스타일 수정

- src/models/audio/useSTT.ts
- src/widgets/interview/Ready/Ready.module.scss
- src/widgets/interview/Ready/index.tsx
interview page의 ready step에 마이크 테스트 UI와 기능 추가
> feat: interview page의 ready step에 마이크 테스트 UI와 기능 추가

- src/widgets/chat/Chat.tsx
면접이 끝나면 답변 제출 버튼의 text가 '면접이 끝났어요!'로 변경됨
면접이 끝났을 경우 답변 제출 버튼의 text 문구 변경
> feat: 면접이 끝났을 경우 답변 제출 버튼의 text 추가

- src/widgets/interview/Stacks/index.tsx
- interview 페이지의 stacks 선택 창에서 아무것도 선택하지 않아도 넘어가는 현상 수정
```
if (!selectedStacks.length) {
return;
}
```
> fix: interview 페이지의 stacks 선택 창에서 아무것도 선택하지 않아도 넘어가는 현상 수정

- src/components/user/UserProfile/UserProfile.module.scss
- src/components/user/UserProfile/index.tsx
- src/widgets/Header/Header.module.scss
- src/widgets/Header/Header.tsx
Header 컴포넌트 style 수정 및 profileImg에 드롭다운 메뉴 추가
> style: Header 컴포넌트 style 수정 및 profileImg에 드롭다운 메뉴 추가

- src/app/(home)/page.module.scss
- src/app/(home)/page.tsx
- src/components/auth/LoginModal/LoginModal.module.scss
- src/components/auth/LoginModal/LoginModal.tsx
- src/shared/components/Button/MovePageBtn/MovePageBtn.module.scss
- src/shared/components/Button/MovePageBtn/MovePageBtn.tsx
- src/shared/store/modalStore.ts
로그인이 되어있지 않은 상태에서 home page의 시작하기 버튼을 눌렀을 경우 로그인 모달이 뜨는 기능 추가
> feat: kakao Login Modal 구현

- src/shared/components/Button/PrimaryBtn/PrimaryBtn.module.scss
- src/widgets/interview/Stacks/Stacks.module.scss
PrimaryBtn과 stack 선택 버튼 UI 변경
PrimaryBtn UI 변경내역
stack 선택 버튼 UI 변경내역
> style: PrimaryBtn과 stack 선택 버튼 UI 변경

- src/widgets/interview/Ready/Ready.module.scss
- src/widgets/interview/Ready/index.tsx
interview/ready의 STT box UI 변경 및 내용물 넘치지 않도록 하는 함수 추가
> interview/ready의 STT box UI 변경 및 내용물 넘치지 않도록 하는 함수 추가

- src/components/chat/chatting/Chatting.module.scss
가독성을 위해서 Chat message Container style을 수정했습니다.
> style: Chat message Container style 수정

- src/widgets/chat/Chat.module.scss
UI 디자인을 위해서 scrollbar style 제거
> style: Chat에서 scrollbar style 제거

- src/component_list/chattingList/ChattingList.tsx
- src/components/chat/chatting/Chatting.module.scss
- src/components/chat/chatting/Chatting.tsx
- src/constants/chat.ts
- src/models/chat/useHandleChat.ts
- src/widgets/chat/Chat.module.scss
- src/widgets/chat/Chat.tsx
chat name을 단순 이름에서 profileImg와 이름으로 변경
> style: chat name을 단순 이름에서 profileImg와 이름으로 변경

- src/widgets/interview/Interviewing/Interviewing.module.scss
interview 페이지의 interviewing step border-radius 통일
- Chat 컴포넌트와 화면 녹화 Display 컴포넌트의 border-radius 12px로 통일
> style: interview 페이지의 interviewing step border-radius 통일

- src/app/interview/InterviewContainer.tsx
- src/models/simulation/useHandleInterview.ts
- src/models/simulation/video.ts
- src/widgets/interview/Interviewing/index.tsx
- src/widgets/interview/Stacks/index.tsx
페이지의 URL이 변경되기 전에 사용자가 stack 리스트를 이용해서 질문을 가져올 경우 URL 변경 전이기 때문에 에러 발생
> refactor: queryString으로 관리하던 선택한 stack 리스트를 useState를 이용한 상태값 관리로 변경

- src/models/audio/useSTT.ts
Reday Step에서 녹음된 텍스트가 Interviewing Step의 첫번째 답변에 들어가는 문제 해결
-  [x] handleStopRecAudio의 SpeechRecognition을 멈추는 메서드를 abortListening에서 stopListening으로 변경
> fix: Reday Step에서 녹음된 텍스트가 Interviewing Step의 첫번째 답변에 들어가는 문제 해결

- src/widgets/interview/Stacks/Stacks.module.scss
interview 페이지의 Stacks Step 반응형 UI에서 Stack의 윗부분 그림자가 짤리는 현상 fix
> fix: interview 페이지의 Stacks Step 반응형 UI에서 Stack의 윗부분 그림자가 짤리는 현상 fix

- src/app/interview/page.module.scss
- src/shared/components/Button/PrimaryBtn/PrimaryBtn.module.scss
- src/widgets/interview/Ready/Ready.module.scss
- src/widgets/interview/Ready/index.tsx
- src/widgets/interview/Stacks/Stacks.module.scss
interview 페이지의 Ready Step 반응형 UI 구현
> style: interview 페이지의 Ready Step 반응형 UI 구현

- src/components/auth/LoginModal/LoginModal.tsx
- src/middleware.ts
- 로그인 모달에 카카오 리다이렉트uri를 환경변수로 변경해주었습니다.
- 미들웨어 코드를 정리하고 첫 진입 페이지와 로그인시 기본 페이지의 명확한 분리를 하였습니다.
> feat: 소개페이지와 메인 서비스 페이지 인증시점 분리작업

- src/components/feedback/FeedbackCard.tsx
- src/widgets/interview/Feedback/index.tsx
- 질문 번호를 추가하여 헤딩부분의 가독성을 향상시켰습니다.
- 카드의 배경을 good or bad or totalFeedback 타입으로 나누어 색상을 특정하였습니다.
> style: 인터뷰 피드백 파트 스타일 개선

- src/components/auth/EmailVerification/index.tsx
- src/components/auth/Policy/index.tsx
- src/components/auth/VerifyForm/index.tsx
- src/mutation/user/updateEmail.ts
- 서버 액션 핸들러의 조건식을 수정하여 확실하게 성공여부를 피드백하도록 하였습니다.
- 성공일 때의 토스트 색상을 blue로 설정하여 가시성을 향상시켰습니다.
> feat: 인증과정에서 토스트를 통해 시각적으로 성공여부 제공
